### ISSUE TITLE
Syntax highlighting no longer works with upgrade to 0.5.1

### ISSUE THREAD

**Issue by Seasawher** [lumeland/theme-simple-blog#13]
Thank you for creating a cute nice template. 

There is a problem with version update.

The following is my `_config.ts` file. (see [whole code](https://github.com/Seasawher/lume) if you need)

```ts
import lume from "lume/mod.ts";
import blog from "https://deno.land/x/lume_theme_simple_blog@v0.5.0/mod.ts";
import date from "lume/plugins/date.ts";
import codeHighlight from "lume/plugins/code_highlight.ts";
import ja from "npm:date-fns/locale/ja/index.js";

const site = lume({
    src: "src",
    dest: "_site",
    server: {
      open: true,
    },
});

site
  .use(blog())
  .remoteFile(
    "_includes/css/code.css",
    // カラーテーマは https://github.com/highlightjs/highlight.js/tree/main/src/styles から好きなものを選ぼう
    "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/styles/github-dark.min.css"
  )
  .use(codeHighlight())
  .use(date({
    locales: { ja },
  }));

export default site;
```

The above code works correctly. However, if the version of lume_theme_simple_blog is upgraded to `v0.5.1` or higher, the syntax highlighting added by `remoteFile` does not work.

**Comment by oscarotero** [comment]
Lume uses this design system: https://github.com/lumeland/ds so the `_includes/css/code.css` file is not longer used.
If you want to customize the styles, you can use the `extra_head` variable. For example, in your `_data.yml` file:

```yml
extra_head: |
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/styles/github-dark.min.css">
```

**Comment by oscarotero** [comment]
Ok, I forgot to mention that the blog doesn't use `highlightjs` for code syntax but [Prism](https://prismjs.com/).

For example, to use the "tomorrow" theme:

```yml
extra_head: |
  <link rel="stylesheet" href="https://unpkg.com/prismjs@1.29.0/themes/prism-tomorrow.css">
```
