### ISSUE TITLE
Feature request: Support for writing posts in .vto files

### ISSUE THREAD

**Issue by shiv19** [lumeland/theme-simple-blog#33]
https://github.com/lumeland/theme-simple-blog/blob/37b91ffede86e99a8858f68f048c2f24dd4aed47/plugins.ts#L67

This theme currently only supports posts in `.md` format. Can we please have support for `.vto` format too.

**Comment by shiv19** [comment]
Probably better to keep it md only when used as a base template.
For advanced use cases it is better to customize the theme.

**Comment by oscarotero** [comment]
`.vto` files are also supported by this theme (althought not by this preprocessor).
Alternatively, you can use the `templateEngine` theme to use vto syntax in md files. Learn more at https://lume.land/docs/core/multiple-template-engines/
