### ISSUE TITLE
archive_result will generate page '/author/object-object/'

### ISSUE THREAD

**Issue by wangbinyq** [lumeland/theme-simple-blog#6]
![image](https://user-images.githubusercontent.com/1384521/194741336-338dc732-0932-4de0-bb37-07d117502c3f.png)

Can we query author with `search.values("author", 'url^=/posts')` or add filter by path/type ?

**Comment by oscarotero** [comment]
This is due a conflict with the `author` variable in the `_data.yml` file.
I just removed it https://github.com/lumeland/theme-simple-blog/commit/ccecb1d2add4cfade819adf810164d07a2f1de2f and now it works fine.

But I like your idea about changing the query. I'd use the `type` variable: `search.values("author", 'type=post')`
